/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scores.proto */

#ifndef PROTOBUF_C_scores_2eproto__INCLUDED
#define PROTOBUF_C_scores_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ScoresMessage ScoresMessage;


/* --- enums --- */


/* --- messages --- */

struct  _ScoresMessage
{
  ProtobufCMessage base;
  /*
   * Array of the player scores, it has -1 when the corresponding player isn't playing
   */
  size_t n_scores;
  int32_t *scores;
};
#define SCORES_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scores_message__descriptor) \
    , 0,NULL }


/* ScoresMessage methods */
void   scores_message__init
                     (ScoresMessage         *message);
size_t scores_message__get_packed_size
                     (const ScoresMessage   *message);
size_t scores_message__pack
                     (const ScoresMessage   *message,
                      uint8_t             *out);
size_t scores_message__pack_to_buffer
                     (const ScoresMessage   *message,
                      ProtobufCBuffer     *buffer);
ScoresMessage *
       scores_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scores_message__free_unpacked
                     (ScoresMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ScoresMessage_Closure)
                 (const ScoresMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor scores_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_scores_2eproto__INCLUDED */
