/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scores.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scores.pb-c.h"
void   scores_message__init
                     (ScoresMessage         *message)
{
  static const ScoresMessage init_value = SCORES_MESSAGE__INIT;
  *message = init_value;
}
size_t scores_message__get_packed_size
                     (const ScoresMessage *message)
{
  assert(message->base.descriptor == &scores_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scores_message__pack
                     (const ScoresMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scores_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scores_message__pack_to_buffer
                     (const ScoresMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scores_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScoresMessage *
       scores_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScoresMessage *)
     protobuf_c_message_unpack (&scores_message__descriptor,
                                allocator, len, data);
}
void   scores_message__free_unpacked
                     (ScoresMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scores_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scores_message__field_descriptors[1] =
{
  {
    "scores",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ScoresMessage, n_scores),
    offsetof(ScoresMessage, scores),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scores_message__field_indices_by_name[] = {
  0,   /* field[0] = scores */
};
static const ProtobufCIntRange scores_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor scores_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScoresMessage",
  "ScoresMessage",
  "ScoresMessage",
  "",
  sizeof(ScoresMessage),
  1,
  scores_message__field_descriptors,
  scores_message__field_indices_by_name,
  1,  scores_message__number_ranges,
  (ProtobufCMessageInit) scores_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
